version: '3.8'

services:
  postgresdb:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: draftbash
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - draftbash-network

  backend:
    build: apps/backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      SPRING_PROFILES_ACTIVE: dev2
    networks:
      - draftbash-network

  frontend:
    build: apps/web-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080/api/v1
      VITE_WEBSOCKET_URL: http://backend:8080/ws
    networks:
      - draftbash-network

volumes:
  postgres-data:

networks:
  draftbash-network:
    driver: bridge