name: Build and deploy container app to Azure Web App - draftbashfantasy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c67c1a0817e432e82407784767150f5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5451e7b1ff7e46158fbbac4a00a015f1 }}

    - name: Install npm dependencies
      run: npm install

    - name: Build and push container image to registry with environment variables
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/sfeddes/draftbash:${{ github.sha }}
        file: ./Dockerfile
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}